name: Docker-scheduled-release 

on:
  schedule:
    - cron: '0 23 * * */7'
  workflow_dispatch:

env:
  IMAGE_NAME: hugo

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get Hugo version
        id: version
        run: echo "::set-output name=version::$(curl https://api.github.com/repos/gohugoio/hugo/releases/latest -s | jq .name -r | cut -c2-)"

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag docker.io/ikstream/$IMAGE_NAME:${{ steps.version.outputs.version}}-${{ steps.date.outputs.date }}
          docker tag docker.io/ikstream/$IMAGE_NAME:${{ steps.version.outputs.version}}-${{ steps.date.outputs.date }} docker.io/ikstream/$IMAGE_NAME:latest

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push image
        run: |
          docker push docker.io/ikstream/$IMAGE_NAME:latest
          docker push docker.io/ikstream/$IMAGE_NAME:${{ steps.version.outputs.version}}-${{ steps.date.outputs.date }}
